'use strict';

/* ============================================================
   Tailwind CSS build config
   ------------------------------------------------------------
   The dashboard ships a PRE-BUILT stylesheet (public/css/tailwind.css)
   so pages need no internet CDN — they work on Render, on a LAN,
   and offline. Rebuild it after changing classes or HTML/JS:

       npm run build:css

   (tailwindcss is a devDependency only — the compiled CSS is
   committed, so production installs never run this.)
   ============================================================ */

module.exports = {
  // Scan every page + client script so JIT picks up every class,
  // including classes built inside JS template strings. The minified
  // 3D-viewer bundle is excluded — it's generated by prismarine-viewer
  // and never uses these utility classes.
  content: ['./public/**/*.html', './public/**/*.js', '!./public/viewer/index.js'],
  theme: {
    extend: {
      // Same font families the old inline configs defined per page.
      fontFamily: {
        pixel: ['"Press Start 2P"', 'monospace'],
        body: ['Inter', 'system-ui', 'sans-serif']
      }
    }
  },
  plugins: []
};
